# Generated by Django 2.2.24 on 2022-05-20 07:22

from django.db import migrations


def calculate_is_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flat_set = Flat.objects.all()
    flat_iterator = flat_set.iterator()
    for flat in flat_iterator:
        flat.new_building = flat.construction_year >= 2015
        flat.save()


def back_to_none_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flat_set = Flat.objects.all()
    flat_iterator = flat_set.iterator()
    for flat in flat_iterator:
        flat.new_building = None
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(calculate_is_new_building, back_to_none_new_building),
    ]
