# Generated by Django 2.2.24 on 2022-05-20 14:48

import phonenumbers
from django.db import migrations


def normalize_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phoneNumber = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(phoneNumber):
            flat.owner_pure_phone = phonenumbers.format_number(phoneNumber,
                                                               phonenumbers.PhoneNumberFormat.INTERNATIONAL)
            flat.save()


def back_to_none_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_auto_20220520_1138'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_number, back_to_none_phone_number),
    ]
