# Generated by Django 2.2.24 on 2022-05-22 11:55

from django.db import migrations


def set_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owner_set = Owner.objects.all()
    owner_iterator = owner_set.iterator()
    for owner in owner_iterator:
        owner.flats.set(Flat.objects.filter(owner=owner.owner))


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0012_auto_20220522_1354'),
    ]

    operations = [
        migrations.RunPython(set_flats),
    ]
